media:
  input: public/images/notes
  output: /images/notes

content:
  - name: notes
    label: Notes
    type: collection
    path: content/notes
    filename: "{year}-{month}-{day}-{primary}.md"
    view:
      fields: [title, date, tags]
      primary: title
      sort: [date, title]
      default:
        sort: date
        order: desc
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: date
        label: Date
        type: date
        required: true
      - name: tags
        label: Tags
        type: string
        list: true
      - name: body
        label: Body
        type: rich-text
